name: find_hotel
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'



dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # flutter_config: ^2.0.0
  flutter_svg: ^2.0.5
  google_maps_flutter: ^2.3.0
  hooks_riverpod: ^2.1.1
  image: ^4.0.17
  riverpod_annotation: ^1.0.6
  uuid: ^3.0.7
  flutter_easyloading: ^3.0.5
  awesome_snackbar_content: ^0.1.3
  flutter_dotenv: ^5.1.0
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.4.0
  shared_preferences: ^2.0.11
  provider: ^5.0.0
  get: ^4.6.5
  encrypt: ^5.0.1
  intl_phone_field: ^3.2.0
  url_launcher: ^6.1.11
  http: ^0.13.1
  geolocator: ^9.0.2
  flutter_google_places: ^0.3.0
  badges: ^3.1.1
  ionicons: ^0.2.2
  geocoding: ^2.1.0
  intl: ^0.17.0
  flutter_config: ^2.0.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_native_splash: ^2.2.9
  

flutter_gen:
  integrations:
    flutter_svg: true
  colors:
    inputs:
      - assets/color/colors.xml

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # run build runner: flutter packages pub run build_runner build --delete-conflicting-outputs
  build_runner: ^2.3.2
  flutter_gen_runner: ^5.1.0+1
  riverpod_generator: ^1.0.6


# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/
    - assets/icon/amenities/
    - assets/image/
    - .env


flutter_native_splash:
  color: "#ffffff"
  image: assets/image/illustration-1.png
  #branding: assets/image/illustration-1.png
  color_dark: "#121212"
  image_dark: assets/image/illustration-1.png
  branding_dark: assets/image/illustration-1.png

  android_12:
    image: assets/image/illustration-1.png
    icon_background_color: "#ffffff"
    image_dark: assets/image/illustration-1.png
    icon_background_color_dark: "#121212"

  web: false




  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/work_sans/WorkSans-Regular.ttf
        - asset: assets/fonts/work_sans/WorkSans-Italic.ttf
          style: italic
        - asset: assets/fonts/work_sans/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/work_sans/WorkSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/work_sans/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/work_sans/WorkSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/work_sans/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/work_sans/WorkSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
    - family:  Icons
      fonts:
      - asset: assets/fonts/Icons.ttf      
flutter_intl:
  enabled: true
