import 'package:flutter/material.dart';

class Car {
  // Nouveaux éléments
  String vehiclesTitle;
  String vehiclesOverview;
  int pricePerDay;
  String fuelType;
  int modelYear;
  int seatingCapacity;
  List<String> image;
  String airConditioner;
  String powerDoorLock;
  String antiLockBrakingSystem;
  String brakeAssist;
  String powerSteering;
  String driveAirBag;
  String passengerAirBag;
  String powerWindows;
  String cdPlayers;
  String centralLocking;
  String crashSensor;
  String leatherSeat;

  // int ratingScore;
  //

  Car(
    this.vehiclesTitle,
    this.vehiclesOverview,
    this.pricePerDay,
    this.fuelType,
    this.modelYear,
    this.seatingCapacity,
    this.image,
    this.airConditioner,
    this.powerDoorLock,
    this.antiLockBrakingSystem,
    this.brakeAssist,
    this.powerSteering,
    this.driveAirBag,
    this.passengerAirBag,
    this.powerWindows,
    this.cdPlayers,
    this.centralLocking,
    this.crashSensor,
    this.leatherSeat,
  );

  static List<Car> allCar = [
    Car(
      "Land Rover",
      "Good for camping",
      20000,
      "diesel",
      2006,
      6,
      [
        "assets/image/land_rover_0.png",
        "assets/image/land_rover_1.png",
        "assets/image/land_rover_2.png",
      ],
      "on",
      "null",
      "on",
      "on",
      "Automatic",
      "null",
      "on",
      "on",
      "null",
      "on",
      "on",
      "null",
    ),
    Car(
      "Alpha Romeo",
      "Apha romeo c4",
      20000,
      "Essence",
      2006,
      5,
      [
        "assets/image/alfa_romeo_c4_0.png",
      ],
      "null",
      "on",
      "on",
      "null",
      "on",
      "Automatic",
      "on",
      "on",
      "null",
      "on",
      "null",
      "on",
    ),
    Car(
      "Acura",
      "MDX 2020",
      2200,
      "Gasoil",
      2004,
      5,
      [
        "assets/image/acura_0.png",
        "assets/image/acura_1.png",
        "assets/image/acura_2.png",
      ],
      "on",
      "null",
      "on",
      "on",
      "Manual",
      "on",
      "null",
      "on",
      "on",
      "null",
      "on",
      "null",
    ),
    Car(
      "Chevrolet",
      "Camaro 2020",
      2200,
      "Diesel",
      2004,
      5,
      [
        "assets/image/camaro_0.png",
        "assets/image/camaro_1.png",
        "assets/image/camaro_2.png",
      ],
      "on",
      "on",
      "null",
      "on",
      "Automatic",
      "on",
      "null",
      "on",
      "null",
      "on",
      "null",
      "on",
    ),
    Car(
      "Ferrari",
      "Spider 488",
      2200,
      "Diesel",
      2004,
      5,
      [
        "assets/image/ferrari_spider_488_0.png",
        "assets/image/ferrari_spider_488_1.png",
        "assets/image/ferrari_spider_488_2.png",
        "assets/image/ferrari_spider_488_3.png",
        "assets/image/ferrari_spider_488_4.png",
      ],
      "on",
      "on",
      "null",
      "on",
      "Automatic",
      "on",
      "null",
      "on",
      "null",
      "on",
      "null",
      "on",
    ),
    Car(
      "Ford",
      "Focus",
      2200,
      "Diesel",
      2004,
      5,
      [
        "assets/image/ford_0.png",
        "assets/image/ford_1.png",
      ],
      "on",
      "on",
      "null",
      "on",
      "Automatic",
      "on",
      "on",
      "on",
      "null",
      "on",
      "on",
      "null",
    ),
    Car(
      "Fiat",
      "500x",
      2000,
      "Diesel",
      2004,
      5,
      [
        "assets/image/fiat_0.png",
        "assets/image/fiat_1.png",
      ],
      "on",
      "on",
      "on",
      "null",
      "manual",
      "on",
      "null",
      "on",
      "null",
      "on",
      "on",
      "on",
    ),
    Car(
      "Honda",
      "Civic",
      2000,
      "Diesel",
      2004,
      5,
      [
        "assets/image/honda_0.png",
      ],
      "on",
      "on",
      "on",
      "null",
      "Automatic",
      "on",
      "null",
      "on",
      "null",
      "on",
      "on",
      "on",
    ),
    Car(
      "Citroen",
      "Picasso",
      2000,
      "Diesel",
      2004,
      5,
      [
        "assets/image/citroen_0.png",
        "assets/image/citroen_1.png",
        "assets/image/citroen_2.png",
      ],
      "on",
      "on",
      "null",
      "on",
      "manual",
      "on",
      "null",
      "on",
      "null",
      "on",
      "null",
      "on",
    ),
  ];
}
